[{'id': 1077, 
'display_name': '15% on KFC남유모달9부돌복01 (WHITE, 
55호) (M, 
GRAY)', 
'activity_ids': [], 
'activity_state': False, 
'activity_user_id': False, 
'activity_type_id': False, 
'activity_type_icon': False, 
'activity_date_deadline': False, 
'my_activity_date_deadline': False, 
'activity_summary': False, 
'activity_exception_decoration': False, 
'activity_exception_icon': False, 
'activity_calendar_event_id': False, 
'message_is_follower': False, 
'message_follower_ids': [6775], 
'message_partner_ids': [47], 
'message_ids': [], 
'has_message': False, 
'message_needaction': False, 
'message_needaction_counter': 0, 
'message_has_error': False, 
'message_has_error_counter': 0, 
'message_attachment_count': 0, 
'rating_ids': [], 
'website_message_ids': [], 
'message_has_sms_error': False, 
'price_extra': 0.0, 
'lst_price': 7900.0, 
'default_code': 'CJFBAJF020003', 
'code': 'CJFBAJF020003', 
'partner_ref': '15% on KFC남유모달9부돌복01 (WHITE, 
55호) (M, 
GRAY)', 
'active': True, 
'product_tmpl_id': (385, 
'15% on KFC남유모달9부돌복01 (WHITE, 
55호)'), 
'barcode': '8808620200136', 
'product_uom_ids': [], 
'product_template_attribute_value_ids': [758, 
756], 
'product_template_variant_value_ids': [758, 
756], 
'combination_indices': '756,758', 
'is_product_variant': True, 
'standard_price': 6320.0, 
'volume': 0.0, 
'weight': 0.0, 
'pricelist_rule_ids': [], 
'product_document_ids': [], 
'product_document_count': 0, 
'additional_product_tag_ids': [], 
'all_product_tag_ids': [], 
'image_variant_1920': b'78.54 Kb', 
'image_variant_1024': b'78.54 Kb', 
'image_variant_512': b'115.65 Kb', 
'image_variant_256': b'35.38 Kb', 
'image_variant_128': b'10.43 Kb', 
'can_image_variant_1024_be_zoomed': False, 
'image_1920': b'78.54 Kb', 
'image_1024': b'78.54 Kb', 
'image_512': b'115.65 Kb', 
'image_256': b'35.38 Kb', 
'image_128': b'10.43 Kb', 
'can_image_1024_be_zoomed': False, 
'write_date': datetime.datetime(2026, 
2, 
25, 
17, 
0, 
4, 
550340), 
'is_favorite': False, 
'is_in_selected_section_of_order': False, 
'create_uid': (20, 
'GB Style'), 
'create_date': datetime.datetime(2025, 
11, 
28, 
4, 
48, 
36, 
960277), 
'write_uid': (101, 
'Integration'), 
'is_image_fetch_pending': False, 
'tax_string': '(= ₩\xa07,182 Excl. Taxes)', 
'stock_quant_ids': [3326], 
'stock_move_ids': [5453, 
5457, 
5459, 
5463, 
5465], 
'qty_available': 15.0, 
'virtual_available': 16.0, 
'free_qty': 15.0, 
'incoming_qty': 1.0, 
'outgoing_qty': 0.0, 
'orderpoint_ids': [], 
'nbr_moves_in': 2, 
'nbr_moves_out': 0, 
'nbr_reordering_rules': 0, 
'reordering_min_qty': 0.0, 
'reordering_max_qty': 0.0, 
'putaway_rule_ids': [], 
'storage_category_capacity_ids': [], 
'show_on_hand_qty_status_button': True, 
'show_forecasted_qty_status_button': True, 
'show_qty_update_button': True, 
'valid_ean': True, 
'lot_properties_definition': [], 
'standard_price_update_warning': False, 
'variant_bom_ids': [538], 
'bom_line_ids': [], 
'bom_count': 3, 
'used_in_bom_count': 0, 
'mrp_product_qty': 15.0, 
'is_kits': False, 
'product_catalog_product_is_in_bom': False, 
'product_catalog_product_is_in_mo': False, 
'purchased_product_qty': 15.0, 
'is_in_purchase_order': False, 
'avg_cost': 0.0, 
'total_value': 0.0, 
'company_currency_id': (32, 
'KRW'), 
'has_image': True, 
'purchase_order_line_ids': [1084], 
'monthly_demand': 0.0, 
'suggested_qty': 0, 
'suggest_estimated_price': 0.0, 
'quality_control_point_qty': 0, 
'quality_pass_qty': 0, 
'quality_fail_qty': 0, 
'sales_count': 0.0, 
'product_catalog_product_is_in_sale_order': False, 
'schedule_count': 0, 
'variant_ribbon_id': False, 
'website_id': False, 
'product_variant_image_ids': [], 
'base_unit_count': 0.0, 
'base_unit_id': False, 
'base_unit_price': 0.0, 
'base_unit_name': 'Units', 
'website_url': '/shop/15-on-kfc남유모달9부돌복01-white-55호-385?attribute_values=255,246', 
'stock_notification_partner_ids': [], 
'printing_printing_method': False, 
'printing_number_of_screens': 0, 
'printing_color': [], 
'bt_so_date': False, 
'bt_so_confirm_date': False, 
'sale_recommended_age': False, 
'sale_kc_certification_status': False, 
'price_rate': 90.0, 
'is_cafe24_synced': True, 
'is_online': True, 
'last_cafe24_sync_date': datetime.datetime(2026, 
2, 
25, 
17, 
0, 
4, 
953388), 
'bss_product_brand_id': (3, 
'첨이첨이'), 
'bss_year': (11, 
'2025'), 
'bss_product_season_id': (3, 
'Fall'), 
'bss_total_sales_qty': 0.0, 
'bss_main_wh_qty': 0.0, 
'bss_main_wh_free_qty': 0.0, 
'bss_branch_qty': 15.0, 
'bss_branch_free_qty': 15.0, 
'website_published': False, 
'is_published': False, 
'can_publish': True, 
'website_absolute_url': 'http://localhost:8019/shop/15-on-kfc남유모달9부돌복01-white-55호-385', 
'is_seo_optimized': False, 
'website_meta_title': False, 
'website_meta_description': False, 
'website_meta_keywords': False, 
'website_meta_og_img': False, 
'seo_name': False, 
'name': '15% on KFC남유모달9부돌복01 (WHITE, 
55호)', 
'sequence': 1, 
'description': False, 
'description_purchase': False, 
'description_sale': False, 
'type': 'consu', 
'combo_ids': [], 
'service_tracking': 'no', 
'categ_id': (153, 
'All / Garments / 홈웨어세트'), 
'currency_id': (32, 
'KRW'), 
'cost_currency_id': (32, 
'KRW'), 
'list_price': 7900.0, 
'volume_uom_name': 'm³', 
'weight_uom_name': 'kg', 
'sale_ok': True, 
'purchase_ok': True, 
'uom_id': (1, 
'Units'), 
'uom_ids': [], 
'uom_name': 'Units', 
'company_id': False, 
'seller_ids': [202, 
275], 
'variant_seller_ids': [202, 
275], 
'color': 4, 
'attribute_line_ids': [398, 
399], 
'valid_product_template_attribute_line_ids': [398, 
399], 
'product_variant_ids': [979, 
1076, 
1077, 
1078, 
1079, 
1541, 
1542, 
1543, 
1544, 
1545, 
1546, 
1547, 
1548, 
1549, 
1550, 
1672, 
1674, 
1676, 
1678, 
1680], 
'product_variant_id': (979, 
'15% on KFC남유모달9부돌복01 (WHITE, 
55호) (XS, 
GRAY)'), 
'product_variant_count': 20, 
'has_configurable_attributes': True, 
'is_dynamically_created': False, 
'product_tooltip': '', 
'product_tag_ids': [], 
'product_properties': [], 
'taxes_id': [1], 
'supplier_taxes_id': [17], 
'property_account_income_id': False, 
'property_account_expense_id': False, 
'account_tag_ids': [], 
'fiscal_country_codes': 'KR', 
'is_storable': True, 
'responsible_id': (20, 
'GB Style'), 
'property_stock_production': (12, 
'Production'), 
'property_stock_inventory': (11, 
'Inventory adjustment'), 
'sale_delay': 0, 
'tracking': 'none', 
'lot_sequence_id': (15, 
'Serial Numbers'), 
'serial_prefix_format': '', 
'next_serial': '0000001', 
'description_picking': False, 
'description_pickingout': False, 
'description_pickingin': False, 
'location_id': False, 
'warehouse_id': False, 
'has_available_route_ids': True, 
'route_ids': [], 
'route_from_categ_ids': [103, 
114, 
66, 
56, 
44, 
52, 
75, 
53, 
94], 
'can_be_expensed': False, 
'bom_ids': [536, 
537, 
538, 
539, 
540, 
541, 
542, 
543, 
544, 
545, 
546, 
547, 
548, 
549, 
550, 
551, 
552, 
553, 
554, 
555, 
327, 
587], 
'purchase_method': 'receive', 
'purchase_line_warn_msg': False, 
'cost_method': 'average', 
'valuation': 'real_time', 
'lot_valuated': False, 
'property_price_difference_account_id': False, 
'version': 1, 
'eco_count': 0, 
'eco_ids': [], 
'available_in_pos': False, 
'to_weight': False, 
'pos_categ_ids': [3], 
'public_description': False, 
'pos_optional_product_ids': [], 
'pos_sequence': 189, 
'service_type': 'manual', 
'sale_line_warn_msg': False, 
'expense_policy': 'no', 
'visible_expense_policy': True, 
'invoice_policy': 'delivery', 
'optional_product_ids': [], 
'product_add_mode': 'configurator', 
'service_to_purchase': False, 
'landed_cost_ok': False, 
'split_method_landed_cost': False, 
'self_order_available': False, 
'self_order_visible': False, 
'expense_policy_tooltip': False, 
'hs_code': False, 
'country_of_origin': False, 
'rating_last_value': 0.0, 
'rating_last_feedback': False, 
'rating_last_image': False, 
'rating_count': 0, 
'rating_avg': 0.0, 
'rating_avg_text': 'none', 
'rating_percentage_satisfaction': -1.0, 
'rating_last_text': False, 
'website_description': False, 
'description_ecommerce': False, 
'alternative_product_ids': [], 
'accessory_product_ids': [], 
'website_size_x': 1, 
'website_size_y': 1, 
'website_ribbon_id': False, 
'website_sequence': 10800, 
'public_categ_ids': [], 
'publish_date': datetime.datetime(2025, 
11, 
28, 
4, 
30, 
35), 
'product_template_image_ids': [], 
'compare_list_price': 0.0, 
'variants_default_code': 'CJFBAJF020001␞CJFBAJF020002␞CJFBAJF020003␞CJFBAJF020004␞CJFBAJF020005␞CJFBAJF020006␞CJFBAJF020007␞CJFBAJF020008␞CJFBAJF020009␞CJFBAJF020010␞CJFBAJF020011␞CJFBAJF020012␞CJFBAJF020013␞CJFBAJF020014␞CJFBAJF020015␞CJFBAJF020016␞CJFBAJF020018␞CJFBAJF020020␞CJFBAJF020022␞CJFBAJF020024', 
'project_id': False, 
'project_template_id': False, 
'task_template_id': False, 
'service_policy': 'delivered_manual', 
'allow_out_of_stock_order': True, 
'available_threshold': 5.0, 
'show_availability': False, 
'out_of_stock_message': False, 
'product_main_type': False, 
'master_attribute_line_ids': [], 
'fabric_attribute_line_ids': [], 
'raw_attribute_line_ids': [], 
'sub_attribute_line_ids': [], 
'printing_attribute_line_ids': [], 
'progress': 0.0, 
'production_progress': 0.0, 
'categ_name': '홈웨어세트', 
'product_brand_id': (3, 
'첨이첨이'), 
'year': (11, 
'2025'), 
'product_season_id': (3, 
'Fall'), 
'product_material_type_id': False, 
'product_material_type': 'printing', 
'product_code': 'F00044', 
'style_number': 2, 
'product_status': False, 
'sale_product_type': False, 
'sale_product_gender': False, 
'sale_product_age': False, 
'sale_product_designer': False, 
'sale_product_bra_level': [], 
'sale_product_designer_user_id': (51, 
'이예지'), 
'sale_product_title': False, 
'sale_product_made_in': False, 
'sale_product_produced_date': '2025-08-08 00:00:00', 
'sale_product_search_words': False, 
'sale_product_sale_description': False, 
'sale_product_product_description': False, 
'sale_product_gbstyle_lines': False, 
'sale_product_line_type': 'character', 
'sale_product_season_selection': [3, 
4], 
'sale_kc_certification_number': False, 
'is_adjustment': False, 
'raw_material_basic_yarn_dyed': False, 
'raw_material_construction': False, 
'raw_material_fabric_kind': False, 
'raw_material_polyurathane': False, 
'raw_material_structure': False, 
'raw_material_fabric_composition': False, 
'raw_material_treatment': False, 
'raw_material_antibacterial': False, 
'raw_material_fabric_classification': False, 
'raw_material_dyeing_method': False, 
'raw_material_fiber': False, 
'raw_material_gauge': False, 
'raw_material_fabric_width': 0.0, 
'raw_material_density': False, 
'raw_material_fabric_description': False, 
'raw_material_weight': 0.0, 
'sub_material_category': (2, 
'Label'), 
'sub_material_size': (19, 
'Side Label'), 
'sub_material_unit': False, 
'printing_dyeing_method': (12, 
'Pigment'), 
'report_color_name': False, 
'report_option_name': False, 
'printing_basic_yarn_dyed': False, 
'printing_construction': 'knit', 
'printing_fabric_kind_id': (2, 
'Gauze'), 
'printing_polyurathane': False, 
'printing_structure_id': (10, 
'Slub'), 
'printing_fabric_composition': 'sd', 
'printing_treatment': False, 
'printing_antibacterial': False, 
'printing_fabric_classification': False, 
'printing_fiber': False, 
'printing_chemical_fiber': False, 
'printing_gauge': False, 
'printing_span_deniar': 0, 
'printing_fabric_width': 0, 
'printing_density': False, 
'printing_fabric_description': False, 
'printing_weight': 0, 
'printing_partner_id': (629, 
'BAOQUAN'), 
'printing_cost': 0.0, 
'printing_cost_kg': 0.0, 
'printing_thickness': False, 
'printing_texture': False, 
'printing_sheerness': False, 
'project_ids': [], 
'task_ids': [], 
'launch_type_id': False, 
'product_age_id': (2, 
'아동'), 
'product_gender_id': (1, 
'공용'), 
'sale_product_display_name': False, 
'sale_product_specification': False, 
'sale_product_size_guide': False, 
'recommended_size_range': False, 
'sale_product_launch_date': datetime.date(2026, 
1, 
15), 
'sale_product_image_url': False, 
'sale_product_detail_image_url': False, 
'sale_product_manufacturer': False, 
'sale_product_vendor': False, 
'detail_page_usp': False, 
'fiber_content': '-', 
'attachment_id': False, 
'work_order_state': 'draft', 
'qc_data_ids': []}]